language: php

php:
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - pecl install ast
  - composer install

script:
  - php ./vendor/bin/phan
  - php ./vendor/bin/psalm
  - mkdir -p build/logs
  - php ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - travis_retry php ./vendor/bin/coveralls

sudo: false
